spring.main.allow-circular-references: true

seata:
  #开启全局事务
  enabled: true
  # 事务服务组
  tx-service-group: my_test_tx_group
  # 开启自动代理数据源，默认为false
  enableAutoDataSourceProxy: true
  #设置seata-server的application-id
  application-id: seata-server
  registry:
    type: nacos
    nacos:
      username: nacos
      password: nacos
      server-addr: 47.99.142.201:8848
      group: SEATA_GROUP
      application: seata-server
      namespace:
  config:
    type: nacos
    nacos:
      application: seata-server
      username: nacos
      password: nacos
      server-addr: 47.99.142.201:8848
      group: SEATA_GROUP
      namespace:
  service:
    # 服务分组映射
    vgroup-mapping:
      # 服务分组: 应用分组
      my_test_tx_group: default
  client:
    rm:
      # 重试次数
      report-retry-count: 5
      #是否上报成功状态
      report-retry-enable: true





